#define IDR_MAIN_WINDOW_MENU            101
#define IDR_TEXTBOX_STATUS_BAR          102
#define ID_MAIN_WINDOW_MENU_FILE_OPEN   40001
#define ID_MAIN_WINDOW_MENU_FILE_SAVE   40002
#define ID_MAIN_WINDOW_MENU_FILE_QUIT   40003
