#define IDR_MAIN_WINDOW_MENU_MDI        101
#define IDR_MAIN_WINDOW_MENU_SDI        102

#define IDR_TEXTBOX_MENU_MDI            103
#define IDR_TEXTBOX_STATUS_BAR          104

#define ID_MAIN_WINDOW_MDI_FILE_OPEN    40001
#define ID_FILE_QUIT                    40002

#define ID_MAIN_WINDOW_SDI_FILE_OPEN    40003
#define ID_MAIN_WINDOW_SDI_FILE_SAVE    40004

#define ID_TEXTBOX_MDI_FILE_SAVE        40005
#define ID_TEXTBOX_MDI_FILE_CLOSE       40006
